name: suitcase
description: A collection of useful personal scripts and tools.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.2.2
  meta: ^1.8.0
  path: ^1.8.2
  universal_io: ^2.0.4
  yaml: ^3.1.1
  yaml_edit: ^2.0.3

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: ^3.0.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
executables:
  suitcase: suitcase
  gho: gho
  dorf: dorf
  forf: forf
  dpga: dpga
  fpga: fpga
